'''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''
count = 0
x = 1
y = 2
stop = 4000000

while x <= stop:
    if x % 2 == 0:
        count += x
    y = x + y
    x = y - x

print count
